apiVersion: v1
kind: PersistentVolume
metadata:
  name: weightapp-pv-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-sc
  local:
    path: /mnt/kube/weightapp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-node-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weightapp-pv-claim
spec:
  storageClassName: local-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: weightapp-pv-volume
